---
- name: Network Commands by Vendor  
  hosts: eosswitches
  gather_facts: no

  vars_files:
    - ~/switch.creds

  tasks:
    - name: Run Arista command
      eos_command:
        commands: show ip int br
      when: ansible_network_os == 'eos'
      register: result

    - name: show result
      debug:
        var: result
