---
- name: Exploring the template module and jinja expressions
  hosts: dte 
  gather_facts: no   # runs the "setup" module on remote hosts

  # these variables are used to build templates
  vars_files:
    - vars/dte.yml


  tasks:
    - name: Configure spaceship registration
      template: 
        src: templates/ship.j2    # name of the template on ansible controller
        dest: ~/ship.cfg              # name of the completed file to be placed on the target system
        
    - name: Configure mission orders
      template:
        src: templates/mission-orders.j2    # name of the template on ansible controller
        dest: ~/mission-orders.txt              # name of the completed file to be placed on the target system

